ckeditor/ckeditor5-linters-config

packages/eslint-config-ckeditor5/.eslintrc.js, packages/eslint-plugin-ckeditor5-rules/lib/index.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/use-require-for-debug-mode-imports.js, packages/eslint-plugin-ckeditor5-rules/tests/use-require-for-debug-mode-imports.js
Internal (eslint-plugin-ckeditor5-rules): Added eslint plugin to disallow using the "import" keyword in debug comments. Closes ckeditor/ckeditor5#12479.
=> Added eslint plugin to disallow using "import" keyword in debug comments

.gitignore, .travis.yml, package.json
Internal: Use `ckeditor5-dev-ci-notify-travis-status` script to send failure notifications on slack.
---
=> Use `ckeditor5-dev-ci-notify-travis-status` script to send failure notifications on slack

packages/eslint-config-ckeditor5/.eslintrc.js
Other (eslint-config-ckeditor5): Allow 'requires' methods not to specify return type.
---
=> Other (eslint-config-ckeditor5): Allow 'requires' methods not to specify return type.

packages/eslint-config-ckeditor5/.eslintrc.js, packages/eslint-plugin-ckeditor5-rules/lib/index.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/ckeditor-error-message.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/ckeditor-imports.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/no-build-extensions.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/no-cross-package-imports.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/no-relative-imports.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/non-public-members-as-internal.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/use-require-for-debug-mode-imports.js, packages/eslint-plugin-ckeditor5-rules/tests/no-build-extensions.js
Feature (eslint-plugin-ckeditor5-rules): Created the `ckeditor5-rules/no-build-extensions` plugin that disallows extending a CKEditor 5 build. Closes ckeditor/ckeditor5#13689.
Other (eslint-plugin-ckeditor5-rules): Added URLs for rule definitions at which the full documentation can be accessed.
---
URL to the rule documentation is helpful, when the rule is violated. Code editors make the URL clickable:
PR with documentation for this new plugin: https://github.com/ckeditor/ckeditor5/pull/13776.
=> Created the `ckeditor5-rules/no-build-extensions` plugin that disallows extending a CKEditor 5 build

packages/eslint-config-ckeditor5/.eslintrc.js, packages/eslint-plugin-ckeditor5-rules/lib/index.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/allow-declare-module-only-in-augmentation-file.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/allow-imports-only-from-main-package-entry-point.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/require-as-const-returns-in-methods.js, packages/eslint-plugin-ckeditor5-rules/tests/allow-declare-module-only-in-augmentation-file.js, packages/eslint-plugin-ckeditor5-rules/tests/allow-imports-only-from-main-package-entry-point.js, packages/eslint-plugin-ckeditor5-rules/tests/require-as-const-returns-in-methods.js
Feature (eslint-plugin-ckeditor5-rules): Created the `ckeditor5-rules/allow-declare-module-only-in-augmentation-file` plugin that enforces using module augmentation for the `@ckeditor/ckeditor5-core` modules only in the augmentation files. Related to ckeditor/ckeditor5#13434.
Feature (eslint-plugin-ckeditor5-rules): Created the `ckeditor5-rules/allow-imports-only-from-main-package-entry-point` plugin that allows imports from the `@ckeditor/*` modules only from the main package entry point. Related to ckeditor/ckeditor5#13434.
Feature (eslint-plugin-ckeditor5-rules): Created the `ckeditor5-rules/require-as-const-returns-in-methods` plugin that enforces using the `as const` in return statements for `requires` and `pluginName` methods. Related to ckeditor/ckeditor5#13434.
Other …
=> Add new eslint rules to ensure good typings generation

packages/eslint-config-ckeditor5/.eslintrc.js
Fix (eslint-config-ckeditor5): Run some TypeScript-specific rules only against `.ts(x)` files. See ckeditor/ckeditor5#13434.
=> Run TypeScript-specific rules only against `.ts(x)` files

packages/eslint-plugin-ckeditor5-rules/lib/rules/allow-declare-module-only-in-augmentation-file.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/allow-imports-only-from-main-package-entry-point.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/require-as-const-returns-in-methods.js
Internal (eslint-plugin-ckeditor5-rules): Updated `meta.docs.url` for recently introduced rules: `ckeditor5-rules/allow-declare-module-only-in-augmentation-file`, `ckeditor5-rules/allow-imports-only-from-main-package-entry-point` and `ckeditor5-rules/require-as-const-returns-in-methods`. See [#13434](https://github.com/ckeditor/ckeditor5/issues/13434) and [#14340](https://github.com/ckeditor/ckeditor5/pull/14340).
---
=> Fix (eslint-plugin-ckeditor5-rules): Update `meta.docs.url` for recently introduced rules

packages/eslint-config-ckeditor5/.eslintrc.js
Fix (eslint-config-ckeditor5): Use `ckeditor5-rules` only for source code, not tests. See ckeditor/ckeditor5#14451.
---
Summary of the changes:
* Run `ckeditor5-rules/*` rules only against source files inside the `src` folder.
* Run `mocha/*` rules only against test files inside the `tests` folder.
=> Use `ckeditor5-rules` only for source code, not tests

packages/eslint-plugin-ckeditor5-rules/package.json
Other (eslint-plugin-ckeditor5-rules): Upgrade the `@es-joy/jsdoccomment` package to its latest version to make the CKEditor 5 compatible with Node@20. Closes ckeditor/ckeditor5#15203.
=> Upgrade to the latest version "@es-joy/jsdoccomment"

packages/eslint-plugin-ckeditor5-rules/lib/rules/allow-declare-module-only-in-augmentation-file.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/allow-declare-module-only-in-augmentation-file.js
Fix (eslint-plugin-ckeditor5-rules): Fixed `ckeditor5-rules/allow-declare-module-only-in-augmentation-file` rule that did not detect the correct path to the augmentation file on Windows due to the use of different path separators. Closes ckeditor/ckeditor5#15426.
---
=> Fixed augmentation rule on Windows OS

packages/eslint-plugin-ckeditor5-rules/lib/rules/require-file-extensions-in-imports.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/require-file-extensions-in-imports.js
Other (eslint-plugin-ckeditor5-rules): Improved the `ckeditor5-rules/require-file-extensions-in-imports` to require a file extension in both imports and exports. See https://github.com/ckeditor/ckeditor5/issues/13673.
---
=> Feat: Add rule requiring file extensions in exports

packages/eslint-plugin-ckeditor5-rules/lib/index.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/no-cross-package-svg-imports.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/no-cross-package-svg-imports.js
Feature (eslint-plugin-ckeditor5-rules): Add a rule to enforce correct imports of the SVG icons. See ckeditor/ckeditor5#15704.
---
=> Add new rule to enforce correct imports of the SVG icons

packages/eslint-plugin-ckeditor5-rules/lib/rules/require-file-extensions-in-imports.js, packages/eslint-plugin-ckeditor5-rules/package.json, packages/eslint-plugin-ckeditor5-rules/tests/rules/require-file-extensions-in-imports.js
Fix (eslint-plugin-ckeditor5-rules): Report a missing file extension when '.' import or export is used. Fixes [#15880](https://github.com/ckeditor/ckeditor5/issues/15880).
Fix (eslint-plugin-ckeditor5-rules): Properly detect valid imports of dependencies using the `exports` field.
---
The first fix results in a problem being reported when using `.` import or export. Previously, this was incorrectly recognized as a valid name of an external dependency.
The second fix ensures that the rule won't report a problem with valid imports of dependencies using the `exports` field in their `package.json` file. Examples:
* https://github.com/ckeditor/ckeditor5/blob/a5b65112c56e9c993c78372c57c9232e0cc1941e/docs/_snippets/framework/tutorials/using-react-in-widget.js#L12-L13
* …
=> Improve validation of the file extensions in imports/exports

packages/eslint-plugin-ckeditor5-rules/lib/rules/require-file-extensions-in-imports.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/require-file-extensions-in-imports.js
Fix (eslint-plugin-ckeditor5-rules): Improve autofixer for `'.'` imports to prepare a relative path to the `index.js` file rather than an absolute path to the imported file. Closes ckeditor/ckeditor5#15880.
---
In #31 we introduced a fix that makes the rule correctly report `'.'` imports as invalid because they do not contain the path to the specific file and file extension. This works fine, but if such an import exists, autofixer doesn't update it to `./index.js' (as it should), but to the absolute path of the file, which is nonsense. This PR fixes the autofixer so that the rule can properly fix this problem by itself.
=> Improve autofix for `'.'` imports

package.json
Internal: Upgraded ckeditor5-dev-* to the latest major version.
---
This repository can be cloned inside the `external/` directory in the CKEditor 5 environment. To avoid package duplications, let's use the same version as CKE5.
=> Upgraded ckeditor5-dev-* to the latest major version

packages/eslint-config-ckeditor5/.eslintrc.js, packages/eslint-plugin-ckeditor5-rules/lib/index.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/ckeditor-plugin-flags.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/ckeditor-plugin-flags.js
Feature (eslint-plugin-ckeditor5-rules): Add the `ckeditor5/ckeditor-plugin-flags` rule that disallows creating certain flags in plugins and enforces proper code style for allowed ones.
Fix (eslint-config-ckeditor5): Disallow defining `isOfficialPlugin` and `isPremiumPlugin` flags in plugins, restricting them to internal use only.
MINOR BREAKING CHANGE: Defining `isOfficialPlugin` and `isPremiumPlugin` flags in plugins is no longer allowed, as they are now restricted to internal use only.
=> Add `ckeditor5/ckeditor-plugin-flags` rule

packages/eslint-plugin-ckeditor5-rules/lib/index.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/allow-svg-imports-only-in-icons-package.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/allow-svg-imports-only-in-icons-package.js
Feature (eslint-plugin-ckeditor5-rules): Add the `allow-svg-imports-only-in-icons-package` rule.
---
Related to ckeditor/ckeditor5#16546.
=> Add the `allow-svg-imports-only-in-icons-package` rule

packages/eslint-config-ckeditor5/eslint.config.mjs
Other: Updated autofixer for `@typescript-eslint/consistent-type-imports` eslint rule. It will now automatically add the `type` keyword in the same import, instead of creating new one, which would cause `duplicate-import` error. Closes ckeditor/ckeditor5#18535
=> Updated eslint config

.changelog/20250707143504_ck_18777_add_rule_to_validate_changelog_entry.md, .circleci/config.yml, eslint.config.mjs, packages/eslint-config-ckeditor5/eslint.config.mjs, packages/eslint-config-ckeditor5/package.json, packages/eslint-plugin-ckeditor5-rules/lib/index.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/validate-changelog-entry.js, packages/eslint-plugin-ckeditor5-rules/package.json, packages/eslint-plugin-ckeditor5-rules/tests/rules/validate-changelog-entry.mjs
* Add and enable the `validate-changelog-entry` rule for validating Markdown-based changelog entries.
* Migrate CI from Machine executors to Docker executors.
---
* See https://github.com/ckeditor/ckeditor5/issues/18777
---
---
I implemented this rule so that it tracks the positions of invalid entries rather than highlighting the entire frontmatter block as invalid. This makes it much easier to locate the issue.
https://github.com/user-attachments/assets/8ccae4f8-6fa8-494f-9c7f-16bd712f946a
---
1. Clone this repo into the `external` folder and check out the `ck/18777-add-rule-to-validate-changelog-entry` branch.
2. Check out the `ck/18777-lint-changelog-entries` branches in the `core` and `commercial` repositories ([core PR](https://github.com/ckeditor/ckeditor5/pull/18827), [commercial …
=> Add and enable the `validate-changelog-entry` rule for validating Markdown-based changelog entries.

.changelog/20250722140239_ck_18857.md, .changelog/20250722145646_ck_18857.md, packages/eslint-plugin-ckeditor5-rules/lib/rules/allow-imports-only-from-main-package-entry-point.js, packages/eslint-plugin-ckeditor5-rules/lib/rules/ckeditor-imports.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/allow-imports-only-from-main-package-entry-point.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/ckeditor-imports.js
- Added a fixer for the `ckeditor5-rules/allow-imports-only-from-main-package-entry-point` rule
- Fixed the `ckeditor5-rules/ckeditor-imports` rule detecting errors for imports that do not start with `ckeditor5`.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/18857
---
*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*
=> Added a fixer for the `ckeditor5-rules/allow-imports-only-from-main-package-entry-point` rule

.changelog/20250929114234_ck_19026.md, package.json, packages/eslint-plugin-ckeditor5-rules/lib/rules/validate-changelog-entry.js, packages/eslint-plugin-ckeditor5-rules/tests/rules/validate-changelog-entry.mjs
Added validation to ensure that changeset files are indented using spaces instead of tabs.
---
* Closes https://github.com/ckeditor/ckeditor5/issues/19026
---
I've additionaly updated the `lint` command to lint all files, so that changeset files are also included.
---
The rule now `validate-changelog-entry` now reports tabs as errors.
```
pnpm run lint
> @ckeditor/ckeditor5-linters-config@12.1.1 lint /home/zanju/repositories/ckeditor5-linters-config
> eslint --quiet "**/*"
/home/zanju/repositories/ckeditor5-linters-config/.changelog/20250929114234_ck_19026.md
40:1  error  Indentation should use spaces instead of tabs  ckeditor5-rules/validate-changelog-entry
44:1  error  Indentation should use spaces instead of tabs  ckeditor5-rules/validate-changelog-entry
45:1  error  Indentation should …
```
=> Changeset indent validation
